server:
  port: 9051
  context-path: /vessel-dev-A
#
#vessel properties
#
vessel:
  vid: 413362260
  states:
   fileName: vesselStates.csv
  locations:
   fileName: locations.xls
   sheetName: ports
  destinations:
   fileName: destinations.xls
   sheetName: ${vessel.vid}
  topic:
   updateShadow: $aws/things/${awsiot.thingName}/shadow/update
   updateStatus: activiti/${awsiot.thingName}/status/change
   activiti: activiti/${awsiot.thingName}/#
   delay: activiti/delay

#
#AWS properties
#
awsiot:
  clientEndpoint: a1cf6tovfozpv3.iot.cn-north-1.amazonaws.com.cn
  clientId: VA${vessel.vid}
  certificate: /home/bqzhu/IdeaProjects/l2l/organization/vessel-A/src/main/resources/vessel.cert.pem
  privateKey: /home/bqzhu/IdeaProjects/l2l/organization/vessel-A/src/main/resources/vessel.private.key
  thingName: vessel
