server:
 port: 9044
 servlet-path: /lvc

#
#custom properties
#
storages:
 fileName: storageRates.csv

# enterprises
logisticsParts:
 fileName: logistics_parts.csv
vesselParts:
 fileName: vessel_parts.csv